version: 2

sphinx:
  configuration: docs/conf.py

formats:
  - htmlzip

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
    rust: "1.78"

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
