import sys

ALL_ASSETS = -1  # the maximum value of uint64_t

DEPTH_EVENT = 1
TRADE_EVENT = 2
DEPTH_CLEAR_EVENT = 3
DEPTH_SNAPSHOT_EVENT = 4
USER_DEFINED_EVENT = 100

WAIT_ORDER_RESPONSE_NONE = -1
WAIT_ORDER_RESPONSE_ANY = -2

UNTIL_END_OF_DATA = sys.maxsize

EXCH_EVENT = 1 << 31
LOCAL_EVENT = 1 << 30

BUY_EVENT = 1 << 29
SELL_EVENT = 1 << 28
